### ISSUE TITLE
WARNING: API 'variant.getJavaCompile()' is obsolete

### ISSUE THREAD

**Issue by CleverMod** [google/protobuf-gradle-plugin#312] opened 2019-05-07 06:54 UTC
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

**Comment by zhangkun83** [comment] 2019-05-07 15:34
This is a duplicate of #295

**Closed by zhangkun83** 2019-05-07 15:34 UTC
