### ISSUE TITLE
Prepare for Gradle v8

### ISSUE THREAD

**Issue by phreed** [google/protobuf-gradle-plugin#515] opened 2021-08-04 17:03 UTC
I get the following error.
```
Using method NamedDomainObjectContainer<T>.invoke(kotlin.Function1) has been deprecated. This is scheduled to be removed in Gradle 8.0. Recompile your plugin against Gradle >= 6.8 Consult the upgrading guide for further information: https://docs.gradle.org/7.1.1/userguide/upgrading_version_6.html#using_NamedDomainObjectContainer_invoke_kotlin_Function1
```
The specific code fragment is
```
protobuf {
   generatedFilesBaseDir = "$projectDir/src/main/java"
   protoc { artifact = "com.google.protobuf:protoc:2.6.1" }
   plugins {
      id("grpc") { artifact = "io.grpc:protoc-gen-grpc-java:1.0.0-pre2" }
   }
}
```
The `plugins` closure is the problematic line.

**Comment by voidzcy** [comment] 2021-09-15 07:12
This is actually a duplicate of #444. We can't really do a migrate without Gradle's latest `org.gradle:gradle-kotlin-dsl` artifact. See details in https://github.com/google/protobuf-gradle-plugin/issues/444#issuecomment-824656691.

**Closed by voidzcy** 2021-09-15 07:12 UTC
Labels: gradle compatibility
