### ISSUE TITLE
generatedFileDir does not follow Gradle Java Plugin conventions (nor can you)

### ISSUE THREAD

**Issue by Xorlev** [google/protobuf-gradle-plugin#16] opened 2015-05-29 06:48 UTC
In the plugin, generatedSourceDir is [always set](https://github.com/google/protobuf-gradle-plugin/blob/e5067815b30ebe2ec91dc71f7f1525a530ac3053/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L240-L243) to `${generatedSourceDir}/${sourceSet.name}`.

Given `generatedFileDir = "${projectDir}/src"`, this dumps the compiled sources into `subproject/src/main/com/test` vs. a more canonical `subproject/src/main/java/com/test`. Since the `sourceSet.name` is always appended to the generatedFileDir, there's no good way to get the latter behavior.

The default behavior of the Java Plugin would be `${project.projectDir}/src/${sourceSet.name}/java`

I'm afraid I'm not familiar enough with Gradle internals to suggest a better solution, but I'd almost rather just be able to say `generatedFileDir = "${projectDir}/src/main/java` and not worry about the sourceSet name.

**Comment by zhangkun83** [comment] 2015-06-01 16:33
This is a duplicate of #13. I think it makes sense to let ``java_out`` to be ``${project.projectDir}/src/${sourceSet.name}/java``.

Then ``javanano_out`` to be ``${project.projectDir}/src/${sourceSet.name}/javanano``, and ``grpc_out`` to be ``${project.projectDir}/src/${sourceSet.name}/grpc``?

**Comment by ejona86** [comment] 2015-06-01 17:14
This actually looks like something the user should be able to configure to be something else. We can by default put it some place, but it should be able to be overridden.

**Comment by debasish-raychawdhuri** [comment] 2015-06-12 14:08
It not only looks bad, but also causes problem in setting up directory structure when sourceSet.name is artificially added to it. Gradle default practice is to have a java directory inside its source set, but its impossible use that structure currently.

**Comment by zhangkun83** [comment] 2015-06-19 23:29
I am working on a new version that will change the default output path to ``"$buildDir/generated/source/proto/$sourceSet/$name"``, where ``$name`` is ``java``, ``python`` etc. This will align with Gradle default practice. I will possibly make the prefix, i.e., ``"$buildDir/generated/source/proto/"`` configurable through a property named ``generatedBaseDir`` if desired.

**Comment by zhangkun83** [comment] 2015-06-19 23:53
> This actually looks like something the user should be able to configure to be something else. We can by default put it some place, but it should be able to be overridden.

@ejona86 Allow overriding the outputDir on the codegen plugin or task granularity is hard to implement correctly (see https://github.com/google/protobuf-gradle-plugin/issues/13#issuecomment-113603639). So far, people have been just wanting that generated files of different codegen plugins can be in separate directories, which doesn't require fine-grained customization.

**Comment by ejona86** [comment] 2015-06-19 23:58
@zhangkun83, how will we commit code generated code? https://github.com/grpc/grpc-java/blob/master/build.gradle#L60

**Comment by zhangkun83** [comment] 2015-06-20 00:22
@ejona86 this is a use case for customizing the base dir, which we can still support.

**Comment by zhangkun83** [comment] 2015-06-22 23:55
Let's move discussions to #13

**Closed by zhangkun83** 2015-06-22 23:55 UTC
