### ISSUE TITLE
Protobuf Lite + Kotlin: Android: Unresolved Reference

### ISSUE THREAD

**Issue by elye** [google/protobuf-gradle-plugin#176] opened 2017-10-23 05:11 UTC
I tried the Android example as much as per the READMe here. My code is in https://github.com/elye/issue_android_protobuf_light. 

The Proto codes got generated. My Android Studio able to find the generated file (e.g. I could import it without error, and the cod autocompletion could find all the generated Proto codes.

However during compilation it complaints `Error:(3, 21) Unresolved reference: proto` (same for other message classes declared). What did I do wrong?

**Comment by elye** [comment] 2017-10-23 09:24
Apparently the issue only happens when it is in Kotlin. As I made the identical code in Java, https://github.com/elye/issue_android_protobuf_light_java, all works fine. Probably some bug to fix or Kotlin to support for Protobuf? (Or something I need to do extra to get it work with Kotlin?)

**Comment by elye** [comment] 2017-11-08 02:48
Checkout the workaround at https://medium.com/@elye.project/android-protobuf-in-kotlin-a1c33014a4e2

**Comment by zpencer** [comment] 2017-12-09 03:22
This looks to be a duplicate of https://github.com/google/protobuf-gradle-plugin/issues/176. I have a PR that adds kotlin support and will be posted soon.

**Closed by zpencer** 2017-12-09 03:22 UTC
Labels: feature request
