### ISSUE TITLE
NullPointerException when building with Jack

### ISSUE THREAD

**Issue by twasilczyk** [google/protobuf-gradle-plugin#73] opened 2016-05-02 17:32 UTC
Example Android project build fails after switching to Jack (new official Android toolchain). This results in inability to migrate to Jack for any project that uses protobuf-gradle-plugin.

To reproduce, apply the patch ([protobuf-gradle-plugin-jack.patch](https://github.com/google/protobuf-gradle-plugin/files/245588/protobuf-gradle-plugin-jack.patch.txt)) and run ```./gradlew test --stacktrace``` ([stack trace](http://pastebin.com/raw/Kiik1HEM)).

**Comment by zhangkun83** [comment] 2016-05-05 20:06
I have contacted Jack developer. It's a known issue to them and hopefully will be fixed in their 2.2 release.

**Closed** 2016-05-05 20:11 UTC

**Comment by mxk** [comment] 2016-06-23 14:40
Do you know if there is an ETA on the 2.2 release? I just tried 2.2.0-alpha3 (assuming you are referring to com.android.tools.build:gradle) and the issue is still there.

**Comment by twasilczyk** [comment] 2016-06-27 12:31
2.2.0-alpha4 works fine for me.

**Comment by mxk** [comment] 2016-06-27 13:43
Thanks for the update. NullPointerException exception is gone, but now I'm getting `ClassNotFoundException: com.android.jack.api.v03.Api03Config` at the `:transformClassesWithPreJackPackagedLibrariesForDebug` step. Guess I'll just wait for the release.
