### ISSUE TITLE
Cannot get Any's'pack()','unpack()' and'is()' methods.

### ISSUE THREAD

**Issue by JackMask** [google/protobuf-gradle-plugin#436] opened 2020-09-29 10:11 UTC
dependencies {
    implementation 'com.android.support:appcompat-v7:27.0.2'

    // You need to build grpc-java to obtain these libraries below.
    implementation 'io.grpc:grpc-okhttp:1.32.1' // CURRENT_GRPC_VERSION
    implementation 'io.grpc:grpc-protobuf-lite:1.32.1' // CURRENT_GRPC_VERSION
    implementation 'io.grpc:grpc-stub:1.32.1' // CURRENT_GRPC_VERSION
    implementation 'org.apache.tomcat:annotations-api:6.0.53'
}

dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
        classpath "com.google.protobuf:protobuf-gradle-plugin:0.8.8"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

![image](https://user-images.githubusercontent.com/13937013/94545396-0bfa7e80-027f-11eb-95a5-5a97b9b49643.png)

**Comment by ejona86** [comment] 2020-09-29 14:32
This is not related to the gradle plugin. I think this is likely https://github.com/protocolbuffers/protobuf/issues/3163 . I think part of the problem is that lite doesn't include the message names in the generated code, which is necessary for the Any convenience methods.

**Comment by voidzcy** [comment] 2020-10-16 07:15
Closing as the issue is irrelevant.

**Closed by voidzcy** 2020-10-16 07:15 UTC

**Comment by kennynicks** [comment] 2020-10-22 11:31
How is this irrelevant or closed? Where is the solution for this?

**Comment by voidzcy** [comment] 2020-10-22 21:31
> How is this irrelevant or closed? Where is the solution for this?

This Protobuf's issue, nothing related to this plugin. You should follow up on https://github.com/protocolbuffers/protobuf/issues/3163.
