### ISSUE TITLE
:generateProto task is not executed in build phase

### ISSUE THREAD

**Issue by uytruong** [google/protobuf-gradle-plugin#641] opened 2022-11-21 04:19 UTC
I'm using IntellJ IDEA with this setting:
![Screen Shot 2022-11-21 at 11 11 21 AM](https://user-images.githubusercontent.com/35051854/202963963-6a5cd344-317d-43c6-9012-7072cb8028cc.png)

Gradle version:
```
------------------------------------------------------------
Gradle 7.3
------------------------------------------------------------

Build time:   2021-11-09 20:40:36 UTC
Revision:     96754b8c44399658178a768ac764d727c2addb37

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_302 (Homebrew 25.302-b00)
OS:           Mac OS X 10.14.6 x86_64
```

Java version is 17

My configuration in build.gradle:
```
buildscript {
    repositories {
        ...
        gradlePluginPortal()
    }
    dependencies {
        ...
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.9.1'
    }
}

plugins {
    ...
    id "com.google.protobuf" version "0.9.1"
}
apply plugin: 'java'

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.21.9'
    }
}

build.dependsOn 'generateProto'

sourceSets {
    main {
        java {
            srcDirs += 'build/generated/source/proto/main/java'
            srcDirs += 'build/src/generated/java'
        }
    }
}
```

When I run `./gradlew build`, the build process jumps into `:compileJava` task instead of executing the `:generateProto` task first

**Comment by rougsig** [comment] 2022-11-21 10:51
Hello. Si it possible to provide a gradle scan? Just run `./gradlew build --scan`, apply gradle terms and send a link from the cosole. It will be in the end of execution.

**Comment by uytruong** [comment] 2022-11-23 06:44
Hi rougsig, I managed it to work with this setting
```
tasks.named("compileJava").configure { dependsOn(generateProto) }
```
Before upgrading to Gradle version 2.7.5, this was the task graph:
```
:build                                                                 (org.gradle.api.DefaultTask)
+--- :assemble                                                         (org.gradle.api.DefaultTask)
|    +--- :bootJar                                                     (org.springframework.boot.gradle.tasks.bundling.BootJar)
|    |    +--- :bootJarMainClassName                                   (org.springframework.boot.gradle.plugin.ResolveMainClassName)
|    |    |    `--- :classes                                           (org.gradle.api.DefaultTask)
|    |    |         +--- :compileJava                                  (org.gradle.api.tasks.compile.JavaCompile)
|    |    |         |    `--- :generateProto                           (com.google.protobuf.gradle.GenerateProtoTask)
|    |    |         |         +--- :extractIncludeProto                (com.google.protobuf.gradle.ProtobufExtract)
|    |    |         |         `--- :extractProto                       (com.google.protobuf.gradle.ProtobufExtract)
|    |    |         `--- :processResources                             (org.gradle.language.jvm.tasks.ProcessResources)
|    |    `--- :classes                                                (org.gradle.api.DefaultTask)
|    |         +--- :compileJava                                       (org.gradle.api.tasks.compile.JavaCompile)
|    |         |    `--- :generateProto                                (com.google.protobuf.gradle.GenerateProtoTask)
|    |         |         +--- :extractIncludeProto                     (com.google.protobuf.gradle.ProtobufExtract)
|    |         |         `--- :extractProto                            (com.google.protobuf.gradle.ProtobufExtract)
|    |         `--- :processResources                                  (org.gradle.language.jvm.tasks.ProcessResources)
|    +--- :distTar                                                     (org.gradle.api.tasks.bundling.Tar)
|    +--- :distZip                                                     (org.gradle.api.tasks.bundling.Zip)
|    `--- :jar                                                         (org.gradle.api.tasks.bundling.Jar)
|         `--- :classes                                                (org.gradle.api.DefaultTask)
|              +--- :compileJava                                       (org.gradle.api.tasks.compile.JavaCompile)
|              |    `--- :generateProto                                (com.google.protobuf.gradle.GenerateProtoTask)
|              |         +--- :extractIncludeProto                     (com.google.protobuf.gradle.ProtobufExtract)
|              |         `--- :extractProto                            (com.google.protobuf.gradle.ProtobufExtract)
|              `--- :processResources                                  (org.gradle.language.jvm.tasks.ProcessResources)
```
which had `:compileJava` task depending on the `:generateProto` task

**Comment by lavanya2290** [comment] 2022-12-19 17:29
same here, the code change done b/w version 0.8.18 and 0.9.1
linkCompileTaskToProto is missing

**Comment by rougsig** [comment] 2022-12-19 17:32
@lavanya2290 Hello it possible to provide a gradle scan? Just run ./gradlew build --scan, apply gradle terms and send a link from the console. Link will be in the end of execution.

**Comment by lavanya2290** [comment] 2022-12-19 17:37
https://gradle.com/s/h7yh76sznip4o

**Comment by lavanya2290** [comment] 2022-12-19 17:44
https://gradle.com/s/gkgonpriluorc

@rougsig

**Comment by rougsig** [comment] 2022-12-19 17:48
@lavanya 2290 in what module did you expect to generate prototypes but it didn't? In that `csp-account-management-proto`, right?

**Comment by lavanya2290** [comment] 2022-12-19 17:50
https://scans.gradle.com/s/xu5ga2322dm3a working one, yes I dont see classes in previous one 0.9.1
This works 0.8.18 version.
you can see classes/compileJava depends on generateProto @rougsig

**Comment by rougsig** [comment] 2022-12-19 17:51
@lavanya2290 could you please add any stub java code to module sources, where proto generation didn't run. And try again.

**Comment by rougsig** [comment] 2022-12-19 17:54
I have a couple of ideas what could be wrong, I'll try it in the week. Thanks for the scans @lavanya2290

**Comment by lavanya2290** [comment] 2022-12-19 17:57
I added new test proto file and rerun the same task build nothing got generated.
I see change done in doApply earlier we have linktodepends on generateProto
linkGenerateProtoTasksToSourceCompile() is there but missing in 0.9.1 version

**Comment by lavanya2290** [comment] 2022-12-19 18:08
This is workaround 
project.tasks.named("compileJava").configure {
            dependsOn 'generateProto'
        }
        

- But pls fix it at earliest

**Comment by rougsig** [comment] 2022-12-19 18:38
@lavanya2290 could you please send your gradle configuration for `sp-account-management-proto`? Do you have java/kotlin/scala/etc sources in that module?

**Comment by lavanya2290** [comment] 2022-12-19 19:15
No its pure java we have just proto file there src/main/proto folder

**Comment by jeffhunter** [comment] 2022-12-19 19:20
We are having the same problem. Our proto module does not contain any Java sources.

**Comment by lavanya2290** [comment] 2022-12-22 02:00
@jeffhunter did u try with workaround

**Comment by jeffhunter** [comment] 2022-12-22 21:45
@lavanya2290 yes, thanks, the workaround fixes it. but a long-term fix would be nice.

**Comment by rougsig** [comment] 2022-12-23 14:44
I've found only one way to reproduce this [bug](https://github.com/rougsig/protobuf-gradle-plugin-641/blob/main/lib/build.gradle#L27).

```gradle
sourceSets {
  main {
    java {
      // replace srcDirs to own array
      srcDirs = ['build/src/generated/java']
    }
  }
}
```

@jeffhunter @lavanya2290
Do you replace `srcDirs` with your own array? If yes, please don't do it. In reason of you replace all sources bindings with your own. It can break not only this plugin.

**Comment by jeffhunter** [comment] 2022-12-23 17:48
@rougsig no, I'm not doing that. this is what my build.gradle file looks like:

```gradle
apply plugin: 'java-library'
apply plugin: 'com.google.protobuf'

sourceSets {
    main {
        proto {
            // In addition to the default 'src/main/proto'
            srcDir "../../../../proto"
        }
        java {
            srcDirs += "${protobuf.generatedFilesBaseDir}/main/java"
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "com.google.protobuf:protobuf-javalite:3.21.9"
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.21.9"
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    option "lite"
                }
            }
        }
    }
}
```

**Comment by rougsig** [comment] 2022-12-23 17:52
@jeffhunter Do you have any `subprojects blocks` or other stuff that can modify `build.gradle` configuration?
Is it full `build.gradle` file or do you have some other plugins/configurations?

**Comment by rougsig** [comment] 2022-12-23 17:56
@jeffhunter I was able to reproduce with your `build.gradle` config. TY!

**Comment by jeffhunter** [comment] 2022-12-23 17:58
@rougsig glad to hear it! that is the full `build.gradle` for our protobuf module.

**Comment by rougsig** [comment] 2022-12-23 18:01
@jeffhunter 

In real you did that:
```
sourceSets {
  main {
    java {
      // replace srcDirs to own array
      srcDirs = ['build/src/generated/java']
    }
  }
}
```

You did `+=` in srcDirs, its means take the current value and replace it with new array. If you wanna add extra folder just write `srcDir "${protobuf.generatedFilesBaseDir}/main/java"` as it said in [docs](https://docs.gradle.org/current/dsl/org.gradle.api.file.SourceDirectorySet.html#org.gradle.api.file.SourceDirectorySet:srcDir(java.lang.Object))

```
Adds the given source to this set.

SourceDirectorySet srcDir(Object srcPath)
```

---

To fix it, try to replace `srcDirs += "${protobuf.generatedFilesBaseDir}/main/java"` to `srcDir "${protobuf.generatedFilesBaseDir}/main/java"`

**Comment by rougsig** [comment] 2022-12-23 18:12
How to fix:

Find in your gradle sourceSet configurations lines like:
- `srcDirs = ['build/src/generated/java']` // pay attention to `=`
- `srcDirs += ['build/src/generated/java']` // pay attention to `+=`

Replace it with:
- `srcDir 'build/src/generated/java'`, 
- `srcDirs 'build/src/generated/java'`

In case of you wanna to replace  `srcDirs` property value with you own value,\
do `compileJava.dependsOn(generateProto)` workaround.

**Closed by rougsig** 2022-12-23 18:12 UTC
Labels: wontfix

**Comment by jeffhunter** [comment] 2022-12-23 18:43
Thanks, that does fix my problem! I'm not sure why we were using `+=` in the first place, but I think I may have originally been looking at the IntelliJ IDEA documentation in `README.md`, which seems to say that `+=` is a way to add additional sources:

```
idea {
    module {
        // proto files and generated Java files are automatically added as
        // source dirs.
        // If you have additional sources, add them here:
        sourceDirs += file("/path/to/other/sources");
    }
}
```

Maybe `+=` does work with the `idea` plugin, I dunno.

In any case, thanks for figuring this out!

**Comment by lavanya2290** [comment] 2022-12-24 04:18
Hi,
But this did work in previous version.
There we never used +=.
So how did it work there.
In plugin it was indeed adding depends on automatically already which is
removed now.

**Comment by rougsig** [comment] 2022-12-24 08:37
@lavanya2290 you have a lot of build-logic internal plugin, did you watch sources of them?

It works in previous version through a couple hacks and tricks. After changes it works though sourceSets on lazy gradle collections. That change give us a simple way to do configuration avoidance logic.

**Comment by lavanya2290** [comment] 2022-12-25 03:41
Can you pls update the documentation as well @rougsig

**Comment by lavanya2290** [comment] 2022-12-25 03:45
```
 void apply(Project project) {

        project.pluginManager.apply("com.google.protobuf")

        project.protobuf {
            protoc {
                artifact = "com.google.protobuf:protoc:3.19.4"
            }
        }

        project.jar {
            from("build/generated/source/proto/main")
        }

        project.sourceSets {
            main {
                java {
                    srcDirs += ["build/generated/source/proto/main"]
                }
            }
        }

    }
```
- Still it does not work
- ./gradlew build does not run generateProto

**Comment by rougsig** [comment] 2022-12-25 13:49
@jeffhunter You replaced `srcDirs += 'path-to-folder'` to `srcDirs 'path-to-folder'`, and all works, right? 
Which documentation update are you referring to?

**Comment by lavanya2290** [comment] 2022-12-25 15:14
Yes right of I change like that it works.

In protobuf gradle plugin we can document it so that others will be
benefited
