### ISSUE TITLE
Error on build in Android Studio 3 Canary & Gradle 4

### ISSUE THREAD

**Issue by TonicArtos** [google/protobuf-gradle-plugin#129] opened 2017-05-19 11:29 UTC
Just testing the new canary release of Android Studio 3, and I am getting this error on build.
```
Error:Could not determine the dependencies of task ':app:extractIncludeDebugProto'.
> Resolving configuration 'debugCompile' directly is not allowed
```
It might be possible to work around in `app/build.gradle` with the protobuf compilation configuration. However, my gradle-fu is insufficient to figure it out right now.

**Comment by zhangkun83** [comment] 2017-05-19 16:36
Looks like it's what #121 set out to fix.

**Comment by dsvoronin** [comment] 2017-05-29 16:52
Seems like #121 is not enough, compile tasks fires before generateXProto

**Comment by LouisCAD** [comment] 2017-06-26 21:36
It's been more than a month since the issue has been reported. Should we move off the gradle plugin, using the plain old CLI, or can we expect the fix to be released in one-two weeks so we can test our projects with Android Studio Canary before it comes to the "stable" channel?

**Comment by zhangkun83** [comment] 2017-06-26 21:43
@rschiu from the Android plugin team is working on the fix #121 . Please follow up with him wrt time line or any other concerns and questions.

**Comment by rschiu** [comment] 2017-07-12 22:37
@dsvoronin Can you explain why you think #121 was not enough?  Is the task dependency incorrect after the fix?

**Comment by bubenheimer** [comment] 2017-07-17 00:40
I managed to work around the issue by isolating the protobuf-related code generation into a separate Android library module, and building that one with Android Gradle Plugin 2.3.2. I had to build the release variant to make it work with the main Android module. It works for my little test project, not sure about production scale.

**Comment by LouisCAD** [comment] 2017-07-17 18:49
@bubenheimer Can you show us a sample of your gradle buildfiles please?

**Comment by bubenheimer** [comment] 2017-07-17 19:35
@LouisCAD Have you tried it? The hard part was figuring out that doing it this way actually works (it does for me). Follow the sample code from the project to fill in the blanks. I have to re-sync with Gradle periodically to make it see the generated code. 2 modules (I have them in the same project, but could likely be separate projects, too):

`androidproto` module (generates Java from `.proto` file):

    buildscript {
        repositories {
            ...
        }

        dependencies {
            classpath 'com.android.tools.build:gradle:2.3.2'
            classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.1'
        }
    }

    apply plugin: 'com.android.library'
    apply plugin: 'com.google.protobuf'

    android {
        compileSdkVersion 26
        buildToolsVersion '26.0.0'

        ...
    }

    protobuf {
        // Use the "lite" approach from the samples
        ...
    }

`app` module:

    buildscript {
        repositories {
            ...
        }
    
        dependencies {
            classpath 'com.android.tools.build:gradle:3.0.0-alpha6'
        }
    }
    
    apply plugin: 'com.android.application'
    
    android {
        compileSdkVersion 26
        buildToolsVersion '26.0.0'
        ...
    }
    
    dependencies {
        implementation project(':androidproto')
        ...
    }

I'm hoping for the fix to be in soon, after all that unfortunate delay, so may not be worth spending too much time on this, unless it's blocking you.

**Comment by LouisCAD** [comment] 2017-07-25 12:36
@bubenheimer Tried on AS 3.0 Canary 8, but I'm still getting the debugCompile error at gradle sync

**Comment by rschiu** [comment] 2017-07-25 22:05
@LouisCAD Can you describe your problem a bit more?  Is the error from the protobuf plugin?  Do you have a stacktrace?  Perhaps there is is other code that is trying to resolve debugCompile?

**Comment by hejie** [comment] 2017-07-27 02:14
on AS 3.0 Canary 8   protobuf

Error:Could not determine the dependencies of task ':app:extractIncludeDebugProto'.
> Resolving configuration 'debugCompile' directly is not allowed

ask for help ，thanks

**Comment by zhangkun83** [comment] 2017-07-28 16:21
IIUC this should have been fixed in #121. I have made the `0.8.2` release to include that change.

**Comment by looperhacks** [comment] 2017-08-01 08:54
I can confirm that this issue is fixed by upgrading to `0.8.2`.

**Closed** 2017-08-01 16:29 UTC

**Comment by LouisCAD** [comment] 2017-09-22 07:18
Hi,
I noticed this Android Gradle plugin 3.0 page still says, wonrgly now, that Protobuf plugin doesn't work. The people in charge of updating this page (if any!) should update it.
Here's the url, cmd+F/ctrl+F fro "proto": https://developer.android.com/studio/build/gradle-plugin-3-0-0.html

**Comment by rschiu** [comment] 2017-09-22 18:08
I will get someone to update the page.  Thanks!
