### ISSUE TITLE
Gradle 5.0 Depreciated API features

### ISSUE THREAD

**Issue by tjoneslo** [google/protobuf-gradle-plugin#253] opened 2018-07-24 13:35 UTC
```
A problem was found with the configuration of task '<task>'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0
 - Directory '/Users/tjoneslo/Documents/workspace/<project>/.out/extracted-include-protos/main' specified for property '$3' does not exist.
```
I get this warning using Gradle 4.6 and protobug-gradle-plugin 0.8.6

**Comment by zhangkun83** [comment] 2018-07-25 22:52
Can you provide a demo project for us to easily reproduce this issue?

**Comment by davidkraus** [comment] 2018-11-20 10:16
same/similar issue:

```
* What went wrong:
A problem was found with the configuration of task ':app:generateDebugProto'.
> Directory '/Users/admin/LocalProjects/MyApplication/app/build/extracted-include-protos/main' specified for property '$3' does not exist.
```

Details:
- Android Project (_com.android.tools.build:gradle:3.4.0-alpha04_) with _kotlin-android_ and _kotlin-android-extensions_ plugins
- Gradle 5.0-milestone-1


attached a sample project

[MyApplication.zip](https://github.com/google/protobuf-gradle-plugin/files/2599178/MyApplication.zip)

**Comment by Zhuinden** [comment] 2018-11-28 00:46
I just wanted to chime in and say we're also getting this warning, and with Gradle 5.0 being released that's a problem.

**Comment by bubenheimer** [comment] 2018-12-24 04:59
I am seeing a similar-looking issue with Gradle 5.0 and protobuf-gradle-plugin 0.8.7. It is a build error, not a warning, and it is a blocker for me. I need to upgrade to Gradle 5.0 to upgrade to errorprone-gradle-plugin 0.6 to upgrade to Dagger 2.20. It looks like this issue has been around for a while and I hope it can be prioritized.

Here's my build output; the various directories correspond to Android productFlavors composing a build variant; I don't think there should be separate directories for these, the only directory needed is `extracted-include-protos/fastNocheckLocalDebug`, and I see that this directory is indeed created, while the others are not:

    Some problems were found with the configuration of task ':app_grpcclient:generateFastNocheckLocalDebugProto'.
    > Directory '/Users/uli/Developer/Android/production/Rucksack/app_grpcclient/build/extracted-include-protos/main' specified for property '$3' does not exist.
    > Directory '/Users/uli/Developer/Android/production/Rucksack/app_grpcclient/build/extracted-include-protos/local' specified for property '$6' does not exist.
    > Directory '/Users/uli/Developer/Android/production/Rucksack/app_grpcclient/build/extracted-include-protos/nocheck' specified for property '$9' does not exist.
    > Directory '/Users/uli/Developer/Android/production/Rucksack/app_grpcclient/build/extracted-include-protos/fast' specified for property '$12' does not exist.
    > Directory '/Users/uli/Developer/Android/production/Rucksack/app_grpcclient/build/extracted-include-protos/fastNocheckLocal' specified for property '$15' does not exist.

**Comment by zhangkun83** [comment] 2018-12-29 01:05
Sorry about the slow response. I have just upgraded the build to Gradle 5.0 (#286) and I am working on adding Gradle 5.0 to the tests. While this particular issue is seemingly straightforward to fix, the tests just start to have various failures with the new Gradle version -- probably not due to bugs of the plugin, but due to the way the tests are written and the way dependencies are wired up. It will take some time to clean things up.

**Comment by xapienz** [comment] 2019-01-02 23:07
Also facing same problem with Gradle 5.0/5.1.
Workaround to unblock this is to manually create those missing dirs (and add creation of directories somewhere into your own build scripts, so it will work in a clean project), and build finishes successfully.

**Comment by zhangkun83** [comment] 2019-01-04 18:35
The issue is not an compatibility issue, but rather a functionality issue with Android plugin >= 2.5. The error from Gradle just makes it more obvious. #287 should fix it, and you can find explanation about this issue on that PR. Can any of you check it out, install it locally (`./gradlew install -x test`) and verify that it works in your project?

**Comment by xapienz** [comment] 2019-01-04 23:58
@zhangkun83 Worked for me, thank you!

**Comment by MrshaoGx** [comment] 2019-01-09 10:06
Facing the same problem. And the build.gradle was worked in version **4.6**. Now,  my gradle version is **5.1**...Is that compatibility problem?

> Directory ' XXX '  specified for property '$3' does not exist.

**Comment by Zhuinden** [comment] 2019-01-09 10:12
you need to use the protobuf plugin in this PR: https://github.com/google/protobuf-gradle-plugin/pull/287

**Comment by MrshaoGx** [comment] 2019-01-09 10:21
> @zhangkun83 

Thanks for reply.

I decide to use version 4.10.3 finally. But i wanna make sure it's gonna work for NESTED build right?

**Comment by Zhuinden** [comment] 2019-01-16 16:31
I see that https://github.com/google/protobuf-gradle-plugin/pull/287 was merged, is there a release scheduled for 0.8.8? ❤️

**Comment by zhangkun83** [comment] 2019-01-16 21:56
0.8.8 is now released.

**Closed by zhangkun83** 2019-01-16 21:56 UTC
Labels: bug, gradle compatibility

**Comment by douruanliang** [comment] 2019-06-05 14:17
I have the same problem ,Android studio 3.4.1  gradle 5.1.1 ，proto setup  
protoc {
            artifact = 'com.google.protobuf:protoc:3.0.0'
        }
        plugins {
            javalite {
                artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
            }
        }
        generateProtoTasks {
            all().each { task ->
                task.builtins {
                    remove java
                }
                task.plugins {
                    javalite { }
                }
            }
        }

**Comment by Zhuinden** [comment] 2019-06-05 14:55
@douruanliang `const val protobuf_gradle_plugin: String = "0.8.8"` ?
