### ISSUE TITLE
Removing a message from a .proto file leads to compile errors

### ISSUE THREAD

**Issue by oehme** [google/protobuf-gradle-plugin#473] opened 2021-02-25 11:52 UTC
The generated Java file for a deleted message is not deleted, but its descriptors are removed from the xxxOuterClass, so compilation fails.

The generator task should clean its output directory before generating.

**Comment by voidzcy** [comment] 2021-02-26 09:43
Duplicate of #331 and #464. We will resolve #332 first.

**Closed** 2021-02-26 11:12 UTC
Labels: duplicate
