### ISSUE TITLE
Does not work with android plugin

### ISSUE THREAD

**Issue by cinnamon25** [google/protobuf-gradle-plugin#11] opened 2015-05-13 11:28 UTC
This plugin does not work with the android plugin for gradle, since it applies the java plugin.

**Comment by ejona86** [comment] 2015-05-13 15:55
Try adding `remove java` within the `builtins` section.

**Comment by AstralStorm** [comment] 2015-05-18 14:58
Same issue, that remove java is not the problem nor fixes it.

The problem is here: https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L70

This protobuf plugin just does not support android plugin.

**Comment by zhangkun83** [comment] 2015-05-20 01:20
The problem with the android plugin is more than just that it cannot be applied when the java plugin has already been applied. The android project is structured differently from a java project.

[Here](https://github.com/zhangkun83/protobuf-gradle-plugin/blob/0fdd127e245dbf7725e9731e55759e353d5c4882/testProjectAndroid/build.gradle) I managed to get the nano protos compiled in an android project. It doesn't look very nice. The Android plugin uses a ``sourceSet`` inside the ``android`` block, not on the top-level. Ideally I should insert the ``proto`` convention to the ``android`` ``sourceSet``, but I haven't figured out how.

**Comment by zhangkun83** [comment] 2015-05-21 01:12
One more android plugin quirk gets in my way.

I tried to have the protobuf plugin to call ``android.sourceSets.<sourceSet>.java.srcDir`` to add generated sources, just like what we have been doing with java plugin. This can only be done in the ``project.afterEvaluate`` hook because only at that point have the proto source sets been evaluated. However, it just doesn't work. It seems the android plugin only reads its source sets BEFORE this point. After that, any changes to its source sets will have no effect.

An experiment to illustrate the problem. In ``ProtobufPlugin.apply``, which is run at ``apply plugin: 'com.google.protobuf'``, if I add the line below, files under ``build/generated-sources/main`` will be compiled.
```groovy
project.android.sourceSets.main.java.srcDir("build/generated-sources/main")
```
If I do this instead, they won't:
```groovy
project.afterEvaluate {
  project.android.sourceSets.main.java.srcDir("build/generated-sources/main")
}
```

This makes it impossible to continue specifying proto files and options inside ``sourceSets`` and make it work with android plugin. I am thinking of using our own conventions/functions to do this, which is more flexible, e.g., we can then manipulate the java sourcesets at evaluation time.

**Comment by zhangkun83** [comment] 2015-05-21 01:27
Anyway, although putting everything in ``sourceSets`` along with the java sources looks very nice from user's aspect, I have been uncomfortable with the fact that the implementation uses Gradle internal API and undocumented internal features. It is very fragile.

**Comment by AstralStorm** [comment] 2015-06-26 17:41
What about com.android.library?

**Comment by zhangkun83** [comment] 2015-06-26 17:44
So, this was unintentionally closed. I have checked in a comprehensive solution for Android, which should  work for both library and application. It will be released as 0.5.0. Soon I will create a release branch for it, and update README in there.

**Comment by zhangkun83** [comment] 2015-06-30 00:21
I have created the [v0.5.x](https://github.com/google/protobuf-gradle-plugin/tree/v0.5.x) branch. Please follow its README and try it out. You may want to refer to [testProjectAndroid](https://github.com/google/protobuf-gradle-plugin/tree/v0.5.x/testProjectAndroid) as a working example for Android.

@madongfly

**Comment by manvelavetisian** [comment] 2015-07-05 02:14
I had manually add dependency to protobuf-nano:

dependencies {
    compile 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-3.1'
}

**Comment by manvelavetisian** [comment] 2015-07-05 04:17
It would be nice to be able to use javanano generated code with java projects and java generated code with android projects though. If I add
        all()*.builtins {
            java {
            }
        }

then it ends up generating both java and javanano classes and compilation fails because it finds duplicate classes.

**Comment by zhangkun83** [comment] 2015-07-05 08:06
@manvelavetisian The ``java`` builtin is added automatically in Java projects, and so is ``javanano`` in Android projects. If you want ``java`` builtin instead in an Android project, you need to remove ``javanano`` explicitly:
```gradle
all()*.builtins {
  remove javanano
  java {
  }
}
```

**Comment by zhangkun83** [comment] 2015-07-06 23:08
0.5.0 has been released. Please refer to the instructions from the master README.

**Closed by zhangkun83** 2015-07-06 23:08 UTC
