### ISSUE TITLE
Another NullPointerException when building with Jack

### ISSUE THREAD

**Issue by twasilczyk** [google/protobuf-gradle-plugin#83] opened 2016-06-28 13:41 UTC
This is a follow-up from #73. While android gradle plugin 2.2.0-alpha4 fixes the first NPE, another two exceptions came out:

`ClassNotFoundException: com.android.jack.api.v03.Api03Config` when trying to deploy a project with Android Studio (was not able to reproduce it with test project, because I got the following NPE at first).

NullPointerException when trying to run `./gradlew test --stacktrace` or `./gradlew assemble` with [protobuf-gradle-plugin-jack-v2.patch](https://github.com/google/protobuf-gradle-plugin/files/337129/protobuf-gradle-plugin-jack-v2.patch.txt) (see [stack trace](https://github.com/google/protobuf-gradle-plugin/files/337130/protobuf-gradle-plugin-stacktrace.txt)).

**Comment by zhangkun83** [comment] 2016-07-06 18:43
Yes I can confirm it.

The problem is that with Jack enabled, the test variants from `android.testVariants` no longer have their `javaCompile` field set. The tasks seems to be gone completely. For example, this works without Jack, but will fail with "task not found" when Jack is enabled:
```
./gradlew testProjectAndroid:compileX86FreeappDebugAndroidTestJavaWithJavac
```

**Comment by zhangkun83** [comment] 2016-07-06 19:25
According to the Android plugin developer, this is to be fixed in alpha5.

**Comment by twasilczyk** [comment] 2016-07-11 09:28
I can confirm alpha5 fixes ClassNotFoundException in my project, but NullPointerException in `./gradlew test` is still there.

**Comment by zhangkun83** [comment] 2016-07-22 22:45
`javaCompile` in `testProjectAndroid/build.gradle` needs to be changed to `javaCompiler` if Jack is enabled. That would solve the NPE.

**Comment by zhangkun83** [comment] 2016-08-09 23:21
@twasilczyk the NPE is an issue only if `testProjectAndroid` enables Jack, and it's not a bug in the plugin. I am closing this issue. Feel free to reopen it if it's not the case.

**Closed by zhangkun83** 2016-08-09 23:21 UTC
